#!/usr/bin/env python
# coding: utf-8

# In[2]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv') 
movies.head(2)
movies.shape
credits.head()
movies = movies.merge(credits,on='title')
movies.head()
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head()
import ast


# In[3]:


def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L 


# In[4]:


movies.dropna(inplace=True)


# In[5]:


movies['genres'] = movies['genres'].apply(convert)
movies.head()


# In[6]:


movies['keywords'] = movies['keywords'].apply(convert)
movies.head()


# In[8]:


import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878,"name":"Science"}]')


# In[9]:


def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L


# In[10]:


movies['cast'] = movies['cast'].apply(convert)
movies.head()


# In[11]:


def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L 


# In[12]:


movies['crew'] = movies['crew'].apply(fetch_director)


# In[13]:


movies.sample(5)


# In[14]:


def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1


# In[15]:


movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)


# In[16]:


movies.head()


# In[17]:


movies['overview'] = movies['overview'].apply(lambda x:x.split())


# In[18]:


movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']


# In[19]:


new = movies.drop(columns=['overview','genres','keywords','cast','crew'])


# In[20]:


new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()


# In[21]:


from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
    


# In[22]:


vector = cv.fit_transform(new['tags']).toarray()


# In[23]:


vector.shape


# In[24]:


from sklearn.metrics.pairwise import cosine_similarity


# In[25]:


similarity = cosine_similarity(vector)


# In[26]:


new[new['title'] == 'The Lego Movie'].index[0]


# In[27]:


def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)
        


# In[28]:


recommend('Gandhi')


# In[30]:


import pickle


# In[33]:


pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

